const appname = "BAC FOOD APP";
const appversion = "Version 1.0.0";
const credits = "@Hoang Bac";
const email = "Email";
const emailHint = "admin@gmail.com";
const password = "Password";
const passwordHint = "******";
const retypePassword = "Retype Password";
const name = "Name";
const nameHint = "Hoang Van Bac";
const forgetPass = "Forget Password";
const login = "Log in";
const signup = "Sign Up";
const createNewAccount = " or, create a new account";
const loginWith = "Log in with";
const privacyPolicy = "Privacy Policy";
const termAndCord = "Terms and Corditions";
const alreadyHaveAccount = "Already Have An Account";
const logout = " Log Out";
const loggedin = "Log in successfully";
const loggedout = "Log out successfully";
const home = "Home",
    categories = " Categories",
    cart = "Cart",
    account = "Account";
const searchanything = "Search any thing...",
    todayDeal = "Today's Deal",
    flashsale = "Flash Sale",
    topSellers = "Top Sellers",
    brand = "Brand",
    topCategories = "Top Categories",
    womenDress = "Cơm",
    girlsWatches = " Girls Watches",
    mobilePhone = " Mobile Phone",
    boyGlasses = "Boy Glasses",
    tShirts = "TShirts",
    girlsDress = "Girls Dresses",
    featuredProduct = " Featured Product",
    featuredCategories = "Featured Categories";
const womenClothing = " Women Clothing",
    menClothingFashion = "Phở",
    compAccess = "Chè",
    automobile = "Trà sữa",
    kidtoys = "Ăn vặt",
    sports = "Đồ nhậu",
    jewelery = "Đồ uống",
    cellphone = "Rượu bia",
    funiture = "Thức ăn nhanh";

const video = " Video",
    reviews = "Reviews",
    sellerpolicy = " Seller Policy",
    returnpolicy = "Return Policy",
    productsyoumatlike = "Products you may also like",
    supportpolicy = " Support Policy";
const wishlist = "My Wishlist",
    order = "My Orders",
    message = "Messages",
    oldpass = "Old password",
    newpass = "New password";
const paypal = "Paypal", stripe = "Stripe", cod = "Cash on delivery";
